name: tsacdop
description: An easy-use podacasts player.

version: 0.2.3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^3.0.1
  sqflite: ^1.3.0 
  flutter_html: ^0.11.1 
  path_provider: ^1.6.7
  color_thief_flutter: ^1.0.2
  provider: ^4.1.0
  google_fonts: ^1.0.0
  dio: ^3.0.9
  file_picker: ^1.6.3+1
  xml: ^3.6.1
  marquee: ^1.3.1
  flutter_downloader: ^1.4.4
  permission_handler: ^5.0.0+hotfix.3
  fluttertoast: ^4.0.1
  intl: ^0.16.1
  url_launcher: ^5.4.5
  image: ^2.1.12
  shared_preferences: ^0.5.7
  uuid: ^2.0.4
  tuple: ^1.0.3
  cached_network_image: ^2.1.0+1
  workmanager: ^0.2.2
  flutter_colorpicker: ^0.3.4
  fl_chart: ^0.9.3
  audio_service: ^0.8.0
  flutter_file_dialog: ^0.0.5
  flutter_linkify: ^3.1.2
  extended_nested_scroll_view: ^0.4.0
  connectivity: ^0.4.8+2
  flare_flutter: ^2.0.3
  rxdart: ^0.24.0
  auto_animated: ^2.0.2  
  just_audio:
    git:
      url: https://github.com/stonega/just_audio.git 
  line_icons:
    git:
      url: https://github.com/galonsos/line_icons.git
dependency_overrides:
  flutter_isolate: '1.0.0+11'
  

flutter:
  assets:
    - assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
