name: tsacdop
description: An easy-use podacasts player.

version: 0.4.8+25

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_animated: ^2.1.0
  audio_service: ^0.11.2
  cached_network_image: ^2.2.0+1
  color_thief_flutter: ^1.0.2
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.9
  dio: ^3.0.9
  extended_nested_scroll_view: ^1.0.1
  effective_dart: ^1.2.4
  feature_discovery: ^0.10.0
  file_picker: ^1.12.0
  flutter_html: ^0.11.1
  flutter_downloader: ^1.4.4
  fluttertoast: ^4.0.0
  flutter_isolate: ^1.0.0+14
  flutter_time_picker_spinner: ^1.0.6+1
  flutter_linkify: ^3.1.3
  flutter_file_dialog: ^0.0.5
  flare_flutter: ^2.0.5
  fl_chart: ^0.10.1
  marquee: ^1.3.1
  google_fonts: ^1.1.0
  image: ^2.1.14
  intl: ^0.16.1
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  path_provider: ^1.6.11
  permission_handler: ^5.0.1
  provider: ^4.3.1
  rxdart: ^0.24.1
  sqflite: ^1.3.1
  shared_preferences: ^0.5.8
  tuple: ^1.0.3
  url_launcher: ^5.5.0
  uuid: ^2.2.0
  xml: ^4.2.0
  workmanager: ^0.2.3
  wc_flutter_share: ^0.2.2
  just_audio:
    git:
      url: https://github.com/stonega/just_audio.git
  line_icons:
    git:
      url: https://github.com/galonsos/line_icons.git
  focused_menu:
    git:
      url: https://github.com/stonega/focused_menu.git
  webfeed:
    git:
      url: https://github.com/stonega/webfeed.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0

flutter:
  assets:
    - assets/
  uses-material-design: true
flutter_intl:
  enabled: true
  localizely:
    project_id: bde4e9bd-4cb2-449b-9de2-18f231ddb47d
