name: tsacdop
description: An easy-use podacasts player.

version: 0.3.4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1
  sqflite: ^1.3.0
  flutter_html: ^0.11.1
  path_provider: ^1.6.8
  color_thief_flutter: ^1.0.2
  provider: ^4.1.2
  google_fonts: ^1.1.0
  dio: ^3.0.9
  file_picker: ^1.9.0+1
  marquee: ^1.3.1
  flutter_downloader: ^1.4.4
  permission_handler: ^5.0.0+hotfix.3
  fluttertoast: ^4.0.1
  intl: ^0.16.1
  url_launcher: ^5.4.7
  image: ^2.1.12
  shared_preferences: ^0.5.7
  uuid: ^2.0.4
  tuple: ^1.0.3
  cached_network_image: ^2.2.0+1
  workmanager: ^0.2.2
  fl_chart: ^0.9.4
  audio_service: ^0.8.0
  flutter_file_dialog: ^0.0.5
  flutter_linkify: ^3.1.3
  extended_nested_scroll_view: ^0.4.0
  connectivity: ^0.4.8+2
  flare_flutter: ^2.0.3
  rxdart: ^0.24.0
  wc_flutter_share: ^0.2.1
  video_player: ^0.10.11
  auto_animated: ^2.1.0
  feature_discovery: ^0.10.0 
  just_audio:
    git:
      url: https://github.com/stonega/just_audio.git
  line_icons:
    git:
      url: https://github.com/galonsos/line_icons.git

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_isolate: "1.0.0+13"
  xml: "4.1.0"

flutter:
  assets:
    - assets/
  uses-material-design: true
flutter_intl:
  enabled: true
