version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:v1.14.6

    branches:
      only: master

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor
      
      - run: echo $ENCODED_KEYSTORE | base64 -di > ${HOME}/keystore.jks
      - run: echo 'export KEYSTORE=${HOME}/keystore.jks' >> $BASH_ENV

      - run:
          name: Build the Android version
          command: flutter build apk --split-per-abi --no-shrink 

      - store_artifacts:
          path: build/app/outputs/apk/release/