version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:stable

    branches:
      only: master

    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor
      - run:
          name: Update package
          command: flutter update-packages --force-upgrade
      - run: echo $ENCODED_KEYSTORE | base64 -di > ${HOME}/keystore.jks
      - run: echo 'export KEYSTORE=${HOME}/keystore.jks' >> $BASH_ENV
      - run: dart tool/env.dart
      - run:
          name: Build the Android version
          command: flutter build appbundle  --obfuscate --split-debug-info=debug/
      - run:
          name: Build the Android apk
          command: flutter build apk --split-per-abi  --obfuscate --split-debug-info=debug/
      - store_artifacts:
          path: build/app/outputs/
