name: Flutter Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
      - run: flutter pub get
      - run: echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
      - run: dart tool/env.dart
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PI_API_SECRET: ${{ secrets.PI_API_SECRET}}
          PI_API_KEY: ${{ secrets.PI_API_KEY}}
      - run: flutter build apk --split-per-abi  --obfuscate --split-debug-info=debug/
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - run: flutter build appbundle  --obfuscate --split-debug-info=debug/
        env:
          API_KEY: ${{ secrets.API_KEY }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
          PI_API_SECRET: ${{ secrets.PI_API_SECRET}}
          PI_API_KEY: ${{ secrets.PI_API_KEY}}
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/**/release/*
