# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - image: cirrusci/flutter:beta

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run flutter doctor
      run: flutter doctor

    # Runs a set of commands using the runners shell
    - name: Update package
      run: flutter update-packages --force-upgrade
    - name: Configure env
      run: |
        echo $ENCODED_KEYSTORE | base64 -di > ${HOME}/keystore.jks
        echo 'export KEYSTORE=${HOME}/keystore.jks' >> $BASH_ENV
        dart tool/env.dart
    - name: Build android version
      run: flutter build appbundle --no-shrink
    
    
