# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.18.0-11.1.pre'
        channel: 'beta'
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
    # Runs a single command using the runners shell
    - name: Run flutter doctor
      run: flutter doctor

    # Runs a set of commands using the runners shell
    - name: Update package
      run: flutter update-packages --force-upgrade
    - name: Configure env
      run: |
        echo $ENCODED_KEYSTORE | base64 -di > /home/runner/work/tsacdop/tsacdop/android/app/keystore.jks
        dart tool/env.dart
    - name: Build android version
      run: flutter build appbundle --no-shrink
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/bundle/release/app-release.aab
    
    
